# -*- coding: utf-8 -*-
"""Password Reminder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10xpPUlOzP6k0z3uphB_N0Us_q8ambrDg

Task : Let's say; you left a message in the past that prints a password you need. To see the password you wrote, you need to enter your name and the program should recognize you.
Write a program that 

Takes the first name from the user and compares it to yours,
Then if the name the user entered is the same as yours, print out such as : "Hello, Joseph! The password is : W@12",
If the name the user entered is not the same as yours, print out such as : "Hello, Amina! See you later."
"""

password = {'sevda': 'wqklj60',
            'fatih': '977h6yd!@',
            'yavuz': 'S34fda@',
            'joseph': '890!.Colarado' 
          }

name = input("Please enter your name :").lower()

if name in password:
  print(f"Hello, {name}! The Password is :", password[name])
else:
  print(f"Hello, {name}! See you later.")



